In [1]:
import pandas as pd
import os
from paths import paths

In [2]:
all_alarm = pd.concat([pd.read_csv(path,usecols=[0,3,5,9,14]) for path in paths])

In [3]:
all_alarm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6348545 entries, 0 to 37019
Data columns (total 5 columns):
RECORD_ID     int64
SOURCE_ID     object
START_TIME    object
SAVE_TIME     object
CLEAR_USER    object
dtypes: int64(1), object(4)
memory usage: 290.6+ MB

In [4]:
all_alarm.head()

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER
0,9748747760,MIX-TNMS_167-颜集-1704-1-1-4-PD2S-07_T_ALOS_2019...,2019-06-19 12:00:00,2019-06-19 12:33:22,AUTOMATIC
1,9748751761,MIX-TNMS_1230-西胡庄-6215-1-1-4-PD2S-04_T_ALOS_20...,2019-06-19 12:00:00,2019-06-19 12:34:10,AUTOMATIC
2,9748754302,MIX-TNMS_462-买臣寺-2251-1-1-4-PD2S-03_T_ALOS_201...,2019-06-19 12:00:00,2019-06-19 12:34:28,AUTOMATIC
3,9771680786,MIX-TNMS_1061-刘百庄-6201-1-1-4-PD2S-03_T_ALOS_20...,2019-06-22 14:00:00,2019-06-22 14:33:35,AUTOMATIC
4,9985277528,MIX-TNMS_508-直路碑-1-1-3-EF8F-03_ETH_LOS_2019-07...,2019-07-25 07:00:00,2019-07-25 07:33:35,AUTOMATIC

In [5]:
all_alarm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6348545 entries, 0 to 37019
Data columns (total 5 columns):
RECORD_ID     int64
SOURCE_ID     object
START_TIME    object
SAVE_TIME     object
CLEAR_USER    object
dtypes: int64(1), object(4)
memory usage: 290.6+ MB

In [7]:
all_alarm['a_flag']=all_alarm['CLEAR_USER'].apply(lambda x:str(x)=='AUTOMATIC')

In [8]:
all_alarm.head()

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER,a_flag
0,9748747760,MIX-TNMS_167-颜集-1704-1-1-4-PD2S-07_T_ALOS_2019...,2019-06-19 12:00:00,2019-06-19 12:33:22,AUTOMATIC,True
1,9748751761,MIX-TNMS_1230-西胡庄-6215-1-1-4-PD2S-04_T_ALOS_20...,2019-06-19 12:00:00,2019-06-19 12:34:10,AUTOMATIC,True
2,9748754302,MIX-TNMS_462-买臣寺-2251-1-1-4-PD2S-03_T_ALOS_201...,2019-06-19 12:00:00,2019-06-19 12:34:28,AUTOMATIC,True
3,9771680786,MIX-TNMS_1061-刘百庄-6201-1-1-4-PD2S-03_T_ALOS_20...,2019-06-22 14:00:00,2019-06-22 14:33:35,AUTOMATIC,True
4,9985277528,MIX-TNMS_508-直路碑-1-1-3-EF8F-03_ETH_LOS_2019-07...,2019-07-25 07:00:00,2019-07-25 07:33:35,AUTOMATIC,True

In [9]:
all_alarm['flag']=all_alarm['SOURCE_ID'].apply(lambda x:str(x).startswith('MIX-'))
all_alarm.head()

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER,a_flag,flag
0,9748747760,MIX-TNMS_167-颜集-1704-1-1-4-PD2S-07_T_ALOS_2019...,2019-06-19 12:00:00,2019-06-19 12:33:22,AUTOMATIC,True,True
1,9748751761,MIX-TNMS_1230-西胡庄-6215-1-1-4-PD2S-04_T_ALOS_20...,2019-06-19 12:00:00,2019-06-19 12:34:10,AUTOMATIC,True,True
2,9748754302,MIX-TNMS_462-买臣寺-2251-1-1-4-PD2S-03_T_ALOS_201...,2019-06-19 12:00:00,2019-06-19 12:34:28,AUTOMATIC,True,True
3,9771680786,MIX-TNMS_1061-刘百庄-6201-1-1-4-PD2S-03_T_ALOS_20...,2019-06-22 14:00:00,2019-06-22 14:33:35,AUTOMATIC,True,True
4,9985277528,MIX-TNMS_508-直路碑-1-1-3-EF8F-03_ETH_LOS_2019-07...,2019-07-25 07:00:00,2019-07-25 07:33:35,AUTOMATIC,True,True

In [10]:
filtered = all_alarm[(all_alarm.flag==False)&(all_alarm.a_flag==True)]
filtered.head()

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER,a_flag,flag
10,10019940940,GNMS-ZC-10.87.76.7-5037110,2019-07-31 00:09:42,2019-07-30 08:09:59,AUTOMATIC,True,False
38,10024787476,TNMS-ZC-PDS-U2000-2-P-EMS;PDS-U2000-2-P;Manage...,2019-07-31 00:05:04,2019-07-30 23:56:01,AUTOMATIC,True,False
39,10024793037,TNMS-ZC-LUH-ANM2000-1-P-大田村街POS004住户-ONU001-FW...,2019-07-31 00:00:10,2019-07-30 23:57:14,AUTOMATIC,True,False
40,10024793723,TNMS-ZC-LUH-ANM2000-1-P-营房街居民区POS001-1住户-ONU00...,2019-07-31 00:00:30,2019-07-30 23:57:36,AUTOMATIC,True,False
41,10024793788,TNMS-ZC-LUH-ANM2000-1-P-NE[13172815]-SLOT[1]-P...,2019-07-31 00:00:27,2019-07-30 23:57:28,AUTOMATIC,True,False

In [11]:
filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6048832 entries, 10 to 37018
Data columns (total 7 columns):
RECORD_ID     int64
SOURCE_ID     object
START_TIME    object
SAVE_TIME     object
CLEAR_USER    object
a_flag        bool
flag          bool
dtypes: bool(2), int64(1), object(4)
memory usage: 288.4+ MB

In [12]:
filtered['START_TIME_PD'] =pd.to_datetime(filtered['START_TIME'])
filtered['SAVE_TIME_PD'] =pd.to_datetime(filtered['SAVE_TIME'])

/Users/zhikuncheng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/zhikuncheng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [45]:
# zero = pd.to_datetime('2019-07-31 00:00:00')
# two_four = pd.to_datetime('2019-08-01 00:00:00')
# filtered = all_alarm[(all_alarm.START_TIME_PD < two_four)] \
#     [all_alarm.START_TIME_PD >= zero]

In [13]:
filtered.head()

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER,a_flag,flag,START_TIME_PD,SAVE_TIME_PD
10,10019940940,GNMS-ZC-10.87.76.7-5037110,2019-07-31 00:09:42,2019-07-30 08:09:59,AUTOMATIC,True,False,2019-07-31 00:09:42,2019-07-30 08:09:59
38,10024787476,TNMS-ZC-PDS-U2000-2-P-EMS;PDS-U2000-2-P;Manage...,2019-07-31 00:05:04,2019-07-30 23:56:01,AUTOMATIC,True,False,2019-07-31 00:05:04,2019-07-30 23:56:01
39,10024793037,TNMS-ZC-LUH-ANM2000-1-P-大田村街POS004住户-ONU001-FW...,2019-07-31 00:00:10,2019-07-30 23:57:14,AUTOMATIC,True,False,2019-07-31 00:00:10,2019-07-30 23:57:14
40,10024793723,TNMS-ZC-LUH-ANM2000-1-P-营房街居民区POS001-1住户-ONU00...,2019-07-31 00:00:30,2019-07-30 23:57:36,AUTOMATIC,True,False,2019-07-31 00:00:30,2019-07-30 23:57:36
41,10024793788,TNMS-ZC-LUH-ANM2000-1-P-NE[13172815]-SLOT[1]-P...,2019-07-31 00:00:27,2019-07-30 23:57:28,AUTOMATIC,True,False,2019-07-31 00:00:27,2019-07-30 23:57:28

In [14]:
import time
filtered['START_TIME_timestamp'] = filtered['START_TIME'].apply(lambda x:time.mktime(time.strptime(x,'%Y-%m-%d %H:%M:%S')))
filtered['SAVE_TIME_timestamp'] = filtered['SAVE_TIME'].apply(lambda x:time.mktime(time.strptime(x,'%Y-%m-%d %H:%M:%S')))

/Users/zhikuncheng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/zhikuncheng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [15]:
filtered.eval('wucha = SAVE_TIME_timestamp - START_TIME_timestamp' , inplace=True)
filtered.head()

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER,a_flag,flag,START_TIME_PD,SAVE_TIME_PD,START_TIME_timestamp,SAVE_TIME_timestamp,wucha
10,10019940940,GNMS-ZC-10.87.76.7-5037110,2019-07-31 00:09:42,2019-07-30 08:09:59,AUTOMATIC,True,False,2019-07-31 00:09:42,2019-07-30 08:09:59,1.564503e+09,1.564445e+09,-57583.0
38,10024787476,TNMS-ZC-PDS-U2000-2-P-EMS;PDS-U2000-2-P;Manage...,2019-07-31 00:05:04,2019-07-30 23:56:01,AUTOMATIC,True,False,2019-07-31 00:05:04,2019-07-30 23:56:01,1.564503e+09,1.564502e+09,-543.0
39,10024793037,TNMS-ZC-LUH-ANM2000-1-P-大田村街POS004住户-ONU001-FW...,2019-07-31 00:00:10,2019-07-30 23:57:14,AUTOMATIC,True,False,2019-07-31 00:00:10,2019-07-30 23:57:14,1.564502e+09,1.564502e+09,-176.0
40,10024793723,TNMS-ZC-LUH-ANM2000-1-P-营房街居民区POS001-1住户-ONU00...,2019-07-31 00:00:30,2019-07-30 23:57:36,AUTOMATIC,True,False,2019-07-31 00:00:30,2019-07-30 23:57:36,1.564502e+09,1.564502e+09,-174.0
41,10024793788,TNMS-ZC-LUH-ANM2000-1-P-NE[13172815]-SLOT[1]-P...,2019-07-31 00:00:27,2019-07-30 23:57:28,AUTOMATIC,True,False,2019-07-31 00:00:27,2019-07-30 23:57:28,1.564502e+09,1.564502e+09,-179.0

In [16]:
filtered[(filtered.wucha>=600)].count()['wucha']

146319

In [17]:
filtered.head()

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER,a_flag,flag,START_TIME_PD,SAVE_TIME_PD,START_TIME_timestamp,SAVE_TIME_timestamp,wucha
10,10019940940,GNMS-ZC-10.87.76.7-5037110,2019-07-31 00:09:42,2019-07-30 08:09:59,AUTOMATIC,True,False,2019-07-31 00:09:42,2019-07-30 08:09:59,1.564503e+09,1.564445e+09,-57583.0
38,10024787476,TNMS-ZC-PDS-U2000-2-P-EMS;PDS-U2000-2-P;Manage...,2019-07-31 00:05:04,2019-07-30 23:56:01,AUTOMATIC,True,False,2019-07-31 00:05:04,2019-07-30 23:56:01,1.564503e+09,1.564502e+09,-543.0
39,10024793037,TNMS-ZC-LUH-ANM2000-1-P-大田村街POS004住户-ONU001-FW...,2019-07-31 00:00:10,2019-07-30 23:57:14,AUTOMATIC,True,False,2019-07-31 00:00:10,2019-07-30 23:57:14,1.564502e+09,1.564502e+09,-176.0
40,10024793723,TNMS-ZC-LUH-ANM2000-1-P-营房街居民区POS001-1住户-ONU00...,2019-07-31 00:00:30,2019-07-30 23:57:36,AUTOMATIC,True,False,2019-07-31 00:00:30,2019-07-30 23:57:36,1.564502e+09,1.564502e+09,-174.0
41,10024793788,TNMS-ZC-LUH-ANM2000-1-P-NE[13172815]-SLOT[1]-P...,2019-07-31 00:00:27,2019-07-30 23:57:28,AUTOMATIC,True,False,2019-07-31 00:00:27,2019-07-30 23:57:28,1.564502e+09,1.564502e+09,-179.0

In [18]:
filtered['wucha'].max()

1029086.0

,RECORD_ID,START_TIME,SAVE_TIME,START_TIME_PD,SAVE_TIME_PD,START_TIME_timestamp,SAVE_TIME_timestamp,wucha
16730,10095394029,2019-07-31 00:11:24,2019-08-11 22:04:00,2019-07-31 00:11:24,2019-08-11 22:04:00,1.564503e+09,1.565532e+09,1029156.0

In [20]:
filtered['wucha'].min()/60

-14700.0

In [22]:
filtered.eval('wucha_min = wucha/60' , inplace=True)

In [23]:
import math
filtered['wucha_min_ceil'] = filtered['wucha_min'].apply(lambda x:math.ceil(x) if x>=0 else math.ceil(x-1))
filtered.head()

/Users/zhikuncheng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,RECORD_ID,SOURCE_ID,START_TIME,SAVE_TIME,CLEAR_USER,a_flag,flag,START_TIME_PD,SAVE_TIME_PD,START_TIME_timestamp,SAVE_TIME_timestamp,wucha,wucha_min,wucha_min_ceil
10,10019940940,GNMS-ZC-10.87.76.7-5037110,2019-07-31 00:09:42,2019-07-30 08:09:59,AUTOMATIC,True,False,2019-07-31 00:09:42,2019-07-30 08:09:59,1.564503e+09,1.564445e+09,-57583.0,-959.716667,-960
38,10024787476,TNMS-ZC-PDS-U2000-2-P-EMS;PDS-U2000-2-P;Manage...,2019-07-31 00:05:04,2019-07-30 23:56:01,AUTOMATIC,True,False,2019-07-31 00:05:04,2019-07-30 23:56:01,1.564503e+09,1.564502e+09,-543.0,-9.050000,-10
39,10024793037,TNMS-ZC-LUH-ANM2000-1-P-大田村街POS004住户-ONU001-FW...,2019-07-31 00:00:10,2019-07-30 23:57:14,AUTOMATIC,True,False,2019-07-31 00:00:10,2019-07-30 23:57:14,1.564502e+09,1.564502e+09,-176.0,-2.933333,-3
40,10024793723,TNMS-ZC-LUH-ANM2000-1-P-营房街居民区POS001-1住户-ONU00...,2019-07-31 00:00:30,2019-07-30 23:57:36,AUTOMATIC,True,False,2019-07-31 00:00:30,2019-07-30 23:57:36,1.564502e+09,1.564502e+09,-174.0,-2.900000,-3
41,10024793788,TNMS-ZC-LUH-ANM2000-1-P-NE[13172815]-SLOT[1]-P...,2019-07-31 00:00:27,2019-07-30 23:57:28,AUTOMATIC,True,False,2019-07-31 00:00:27,2019-07-30 23:57:28,1.564502e+09,1.564502e+09,-179.0,-2.983333,-3

In [24]:
grouped = filtered.groupby('wucha_min_ceil')
result=grouped.describe()['RECORD_ID']

In [25]:
result.to_csv('result.csv')